name: Repo Metadata Puller for repos_list_0
run-name: Pulling Repo Metadata
on: 
  schedule:
    - cron: "8 16 * * *"
jobs:
  Run-reusable-metadata-puller:
    uses: ./.github/workflows/reusable-repo-metadata-puller.yml
    with:
      repos_list_path: ../config/repos_list_dir/repos_list_0.json
    secrets:
      do_key_id: ${{ secrets.DO_KEY_ID }}
      do_key_secret: ${{ secrets.DO_KEY_SECRET }}
