name: Repo Metadata Puller for repos_list_1
run-name: Pulling Repo Metadata
on: 
  schedule:
    - cron: "38 16 * * *"
jobs:
  Run-reusable-metadata-puller:
    uses: ./.github/workflows/reusable-repo-metadata-puller.yml
    with:
      repos_list_path: ../config/repos_list_dir/repos_list_1.json
